// <auto-generated />
namespace MiniFB.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DataURLProp_On_NewsFeedItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataURLProp_On_NewsFeedItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201305300910599_DataURLProp_On_NewsFeedItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
