// <auto-generated />
namespace MiniFB.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LikeEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LikeEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201306181358187_LikeEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
